version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: es01
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kib01
    restart: unless-stopped
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
